### ISSUE TITLE
PDF Export doesn't work?

### ISSUE THREAD

**Issue by psychemedia** [fomightez/jupyter-rise_with-hide_code#1]
Trying the Binder demo, neither PDF export works for me? I just get redirected to a non-existent page?

**Comment by fomightez** [comment]
Thanks for trying it. I think [a very recent update](https://github.com/kirbs-/hide_code/pull/83#issuecomment-587034204) may have broken it overnight because it no longer works [here](https://github.com/fomightez/jupyter_hide_code) which is where I developed and tested using hide_code extension in Binder sessions thoroughly. I'll need to dig into more the next few days and see if rolling back the version fixes it for now. The [extension author didn't think the bootstrapping approach](https://github.com/kirbs-/hide_code/pull/83#issuecomment-587034204) I had found and built-in to make it work was necessary. And I wonder if what I was using for the approach has now been altered/removed. 

On the positive side, I made the extension author aware of Binder and seems receptive making it work there.

**Comment by fomightez** [comment]
Fixed it for now by pinning to older version. PDF export works again. (Also the hide_code extension with PDF export support works [here](https://github.com/fomightez/jupyter_hide_code) via Binder but without Jupyter-RISE included.) This is meant to be temporary as the extension author has made an update that is more full-featured and it will be nice to have current version of the extension working alongside Jupyter-RISE served by Binder eventually.
